
[project]
name = "My_CRL_Agents"
version = "0.1.0"
description = ""
authors = [
    {name = "ssghost", email = "ssprof0@gmail.com"},
]
dependencies = []
requires-python = ">=3.8"
readme = "README.md"
license = {text = "MIT"}

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"
